defiance: ns3::PowerControlMobComEnv Class Reference
ns3::PowerControlMobComEnv Class Reference
defiance
Single agent environment for training power control with reinforcement learning.
#include "pc-environment.h"
Public Member Functions
void AddTraffic () override
Overwrite to add internet traffic to the scenario. Include 1. Routing and IPs, 2. Attaching UEs and eNbs, and 3. Registering applications.
void CreateBsLine (uint16_t numBSs, uint64_t lineLength)
void CreateMultiBsTopology ()
void CreateRandomFixedTopology (uint16_t numUEs, uint16_t numBSs, uint64_t lineLength)
void CreateSimpleTopology (Vector position, Vector velocity)
void CreateTopology () override
Fill containers for UEs and base stations. The specific topology has to be specified in the child class.
bool ExecuteActions (Ptr< OpenGymDataContainer > action) override
Ptr< OpenGymSpace > GetActionSpace () override
std::map< std::string, std::string > GetExtraInfo () override
Ptr< OpenGymDataContainer > GetObservation () override
std::vector< uint32_t > GetObservationShape ()
Ptr< OpenGymSpace > GetObservationSpace () override
float GetReward () override
MobComEnv ()
MobComEnv (Time simulationDuration, Time notificationRate, Time notificationStart)
Constructor for the MobComEnv class.
void ParseCliArgs (int argc, char *argv[])
void RegisterCallbacks () override
Register the necessary callbacks for tracing.
void SetScenarioAttributes () override
Override this method in the child class to set global attributes, or attributes specific to the LteHelper or EpcHelper. In case you do not override this method, default values will be used. Example for setting the Propagation Model: GetLteHelper()->SetPathlossModelType(TypeId::LookupByName("ns3::RangePropagationLossModel")); GetLteHelper()->SetPathlossModelAttribute("MaxRange", DoubleValue(2000));.
void SetupScenario () override
Template method for scenario creation. Customize it by overriding SetScenarioAttributes(), ScheduleNotificationEvents(), CreateTopology(), AddTraffic() and RegisterCallbacks().
std::map< std::string, std::string > sinrVecToMap ()
Public Member Functions inherited from ns3::MobComEnv
MobComEnv (Time simulationDuration, Time notificationRate, Time notificationStart)
Constructor for the MobComEnv class.
void DoDispose () override
DeviceManager * GetDeviceManager ()
Ptr< EpcHelper > GetEpcHelper ()
std::map< std::string, std::string > GetExtraInfo () override
bool GetGameOver () override
Always return false here, as mobile environments are continous. This becomes the terminated field in Gymnasium. Use a TimeLimit object to truncate the environment after a given amount of steps.
Ptr< LteHelper > GetLteHelper ()
Time GetSimulationDuration ()
Public Attributes
std::string arg_handoverAlgorithm = "ns3::NoOpHandoverAlgorithm"
double arg_noiseFigure = 9
std::string arg_propagationModel = "ns3::FriisPropagationLossModel"
double arg_speed = 0
std::string arg_topology = "simple"
int cbCalls = 0
std::vector< float > powers
std::vector< float > powersMeasured
std::vector< std::vector< float > > sinrs
Additional Inherited Members
Static Public Member Functions inherited from ns3::MobComEnv
static TypeId GetTypeId ()
Get the type ID.
Protected Member Functions inherited from ns3::MobComEnv
void AttachUEsToEnbs ()
Attach user equipment to base stations. By default, each UE is attached to the closest base station.
void ScheduleNotificationEvents ()
Schedule the Notify() events according to m_notificationRate.
Protected Attributes inherited from ns3::MobComEnv
DeviceManager * m_deviceManager
Ptr< EpcHelper > m_epcHelper
Ptr< LteHelper > m_lteHelper
const Time m_notificationRate
const Time m_notificationStart
const Time m_simulationDuration
Maximum duration of the simulation Default = Seconds(200);.
Detailed Description
Single agent environment for training power control with reinforcement learning.
Definition at line 22 of file pc-environment.h.
Member Function Documentation
AddTraffic()
void PowerControlMobComEnv::AddTraffic () override virtual
Overwrite to add internet traffic to the scenario. Include 1. Routing and IPs, 2. Attaching UEs and eNbs, and 3. Registering applications.
See also
static-environment.cc
Implements ns3::MobComEnv.
Definition at line 176 of file pc-environment.cc.
References ns3::MobComEnv::AttachUEsToEnbs(), and ns3::MobComEnv::GetDeviceManager().
MobComEnv()
ns3::MobComEnv::MobComEnv
Constructor for the MobComEnv class.
Parameters
simulationDuration the maximum of the simulation.
notificationRate the rate at which Notify() should be called to send the observations to python and get the agent's actions.
notificationStart the time at which the first notification should be sent.
Definition at line 35 of file base-environment.cc.
References ns3::MobComEnv::AddTraffic(), ns3::MobComEnv::CreateTopology(), ns3::MobComEnv::RegisterCallbacks(), ns3::MobComEnv::ScheduleNotificationEvents(), and ns3::MobComEnv::SetScenarioAttributes().
The documentation for this class was generated from the following files:
pc-environment.h
pc-environment.cc
pc-simulation.cc