defiance: ns3::TimestampedDataDeque Class Reference
ns3::TimestampedDataDeque Class Reference
defiance
A class to store observation/reward data with timestamps in a deque. The class provides basic methods for manipulation of the deque.
#include "history-container.h"
Public Member Functions
void Clear ()
Clear the deque.
std::vector< TimestampedData * > GetAll ()
Get all data entries from the deque.
std::vector< TimestampedData * > GetNewest (uint count=1)
Get the count newest data entries from the deque.
std::vector< TimestampedData * > GetOldest (uint count=1)
Get the count oldest data entries from the deque.
void PopNewest (uint count=1)
Remove the count newest data entries from the deque.
void PopOldest (uint count=1)
Remove the count oldest data entries from the deque.
void Push (TimestampedData value)
Add a new data entry to the deque.
uint Size () const
Detailed Description
A class to store observation/reward data with timestamps in a deque. The class provides basic methods for manipulation of the deque.
Definition at line 50 of file history-container.h.
Member Function Documentation
GetAll()
std::vector< TimestampedData * > TimestampedDataDeque::GetAll ()
Get all data entries from the deque.
Returns
a vector of data entries.
Definition at line 75 of file history-container.cc.
References GetNewest(), and Size().
GetNewest()
std::vector< TimestampedData * > TimestampedDataDeque::GetNewest (uint count = 1)
Get the count newest data entries from the deque.
Returns
a vector of data entries.
Definition at line 63 of file history-container.cc.
Referenced by GetAll(), and ns3::HistoryContainer::GetNewestOfCombinedHistory().
GetOldest()
std::vector< TimestampedData * > TimestampedDataDeque::GetOldest (uint count = 1)
Get the count oldest data entries from the deque.
Returns
a vector of data entries.
Definition at line 51 of file history-container.cc.
Size()
uint TimestampedDataDeque::Size () const
Returns
the size of the deque.
Definition at line 87 of file history-container.cc.
Referenced by GetAll(), ns3::HistoryContainer::GetSizeOfHistory(), and ns3::HistoryContainer::Push().
The documentation for this class was generated from the following files:
history-container.h
history-container.cc