defiance: ns3::HistoryContainer Class Reference
ns3::HistoryContainer Class Reference
defiance
The main datastructure to store observation/reward data from different observation/reward spaces. It stores different deques for each observation/reward space m_deques and a history deque containing all data m_historydeque. The number of last data to store each observation/reward space deque is defined by m_historyLimit and the number of observation/reward spaces is defined by m_dequeNumber. The class provides methods to manage the data.
#include "history-container.h"
Public Member Functions
HistoryContainer (uint historyLimit, bool trackNs3Time=false)
Creates a new HistoryContainer object.
std::map< std::string, AggregatedInfo > AggregateNewest (uint id, uint n=1)
Aggregate the latest n data entries of the specified history deque.
void DeleteHistory (uint id)
Delete an existing history if it exists.
uint GetHistoryCount () const
Retrieve the number of different histories in the container.
TimestampedData * GetNewestByID (uint id)
Retrieve the latest data entry of a history deque.
std::vector< TimestampedData * > GetNewestByID (uint id, uint n)
Retrieve the latest n collected data entries of one history deque.
TimestampedData * GetNewestOfCombinedHistory ()
Aggregate the latest data entry of all history deques.
std::vector< TimestampedData * > GetNewestOfCombinedHistory (uint n)
Retrieve the latest n data entries of all history deques.
uint GetSize (uint id)
Retrieve the size of a certain history deque.
uint GetSizeOfHistory ()
Retrieve the size of the combined history deque. The size can be larger than the sum of the sizes of the individual history deques, because the combined history deque contains at most m_historyLength * m_historyCount data entries. Thus, if some history deques receive data entries more frequently than others, the combined history deque can contain more entries of that deque than m_historyLength.
bool HistoryExists (uint id)
Check whether a certain history deque exists without an assertion.
void Print (std::ostream &where)
Print type and size information of each history deque.
void PrintHistory (std::ostream &where, uint id, ns3_ai_gym::SpaceType type=ns3_ai_gym::Box)
Print all stored data entries of a certain history deque.
void Push (Ptr< OpenGymDictContainer > data, uint id)
Push data into a certain history deque. If no history with the given ID exists, a new history is created.
Detailed Description
The main datastructure to store observation/reward data from different observation/reward spaces. It stores different deques for each observation/reward space m_deques and a history deque containing all data m_historydeque. The number of last data to store each observation/reward space deque is defined by m_historyLimit and the number of observation/reward spaces is defined by m_dequeNumber. The class provides methods to manage the data.
Definition at line 110 of file history-container.h.
Constructor & Destructor Documentation
HistoryContainer()
HistoryContainer::HistoryContainer (uint historyLimit, bool trackNs3Time = false)
Creates a new HistoryContainer object.
Parameters
m_historyLimit the number data entries to store in each observation/reward space deque before overwriting the oldest data.
trackNs3Time boolean to decide whether the ns3 simulation time should be tracked with every data entry.
Definition at line 92 of file history-container.cc.
Member Function Documentation
AggregateNewest()
std::map< std::string, AggregatedInfo > HistoryContainer::AggregateNewest (uint id, uint n = 1)
Aggregate the latest n data entries of the specified history deque.
Parameters
n the number of data entries to aggregate.
id the ID of the history deque.
Returns
a map with the keys of the dictionary and the aggregated information for each key.
Definition at line 147 of file history-container.cc.
References GetNewestByID().
Referenced by ns3::TestAgentApp::OnRecvObs(), and ns3::TestAgentApp::OnRecvReward().
DeleteHistory()
void HistoryContainer::DeleteHistory (uint id)
Delete an existing history if it exists.
Parameters
id th ID of the history deque that should be deleted.
Definition at line 322 of file history-container.cc.
GetHistoryCount()
uint HistoryContainer::GetHistoryCount () const
Retrieve the number of different histories in the container.
Returns
number of history deques.
Definition at line 104 of file history-container.cc.
GetNewestByID() [1/2]
TimestampedData * HistoryContainer::GetNewestByID (uint id)
Retrieve the latest data entry of a history deque.
Parameters
id the ID of the history deque.
Returns
the newest data entry of the history deque.
Definition at line 230 of file history-container.cc.
References GetNewestByID().
GetNewestByID() [2/2]
std::vector< TimestampedData * > HistoryContainer::GetNewestByID (uint id, uint n)
Retrieve the latest n collected data entries of one history deque.
Parameters
n the number of data entries to return.
id the ID of the history deque.
Returns
a vector with the newest n data entries.
Definition at line 223 of file history-container.cc.
Referenced by AggregateNewest(), and GetNewestByID().
GetNewestOfCombinedHistory() [1/2]
TimestampedData * HistoryContainer::GetNewestOfCombinedHistory ()
Aggregate the latest data entry of all history deques.
Returns
the newest data entry.
Definition at line 236 of file history-container.cc.
GetNewestOfCombinedHistory() [2/2]
std::vector< TimestampedData * > HistoryContainer::GetNewestOfCombinedHistory (uint n)
Retrieve the latest n data entries of all history deques.
Parameters
n the number of data entries to return.
Returns
a vector with the newest n data entries.
Definition at line 217 of file history-container.cc.
References ns3::TimestampedDataDeque::GetNewest().
GetSize()
uint HistoryContainer::GetSize (uint id)
Retrieve the size of a certain history deque.
Parameters
id the ID of the history deque.
Returns
the size of the specified history deque.
Definition at line 242 of file history-container.cc.
GetSizeOfHistory()
uint HistoryContainer::GetSizeOfHistory ()
Retrieve the size of the combined history deque. The size can be larger than the sum of the sizes of the individual history deques, because the combined history deque contains at most m_historyLength * m_historyCount data entries. Thus, if some history deques receive data entries more frequently than others, the combined history deque can contain more entries of that deque than m_historyLength.
Returns
the size of the combined history deque.
Definition at line 249 of file history-container.cc.
References ns3::TimestampedDataDeque::Size().
HistoryExists()
bool HistoryContainer::HistoryExists (uint id)
Check whether a certain history deque exists without an assertion.
Parameters
id the ID of the history deque.
Returns
true if the history exists, false otherwise.
Definition at line 141 of file history-container.cc.
Print()
void HistoryContainer::Print (std::ostream & where)
Print type and size information of each history deque.
Parameters
where the stream to print the data entries to.
Definition at line 255 of file history-container.cc.
PrintHistory()
void HistoryContainer::PrintHistory (std::ostream & where, uint id, ns3_ai_gym::SpaceType type = ns3_ai_gym::Box)
Print all stored data entries of a certain history deque.
Parameters
where the stream to print the data entries to
id the ID of the history deque.
type the space type of the data entry. Currently only ns3_ai_gym::Box is supported with data of type uint, float, uint32_t or double.
Definition at line 271 of file history-container.cc.
Push()
void HistoryContainer::Push (Ptr< OpenGymDictContainer > data, uint id)
Push data into a certain history deque. If no history with the given ID exists, a new history is created.
Parameters
data the data to push.
id the ID of the history deque data should be pushed to.
Definition at line 110 of file history-container.cc.
References ns3::TimestampedDataDeque::PopOldest(), ns3::TimestampedDataDeque::Push(), and ns3::TimestampedDataDeque::Size().
The documentation for this class was generated from the following files:
history-container.h
history-container.cc