defiance: SimpleChannelInterface Class Reference
SimpleChannelInterface Class Reference
defiance
A very basic implementation of a communication channel that allows the user to specify a delay for propagation. It must always be used in connection with another simple channel interface object.
#include "simple-channel-interface.h"
Public Member Functions
ConnectionStatus Connect (Ptr< ChannelInterface > otherInterface) override
Establish a connection to the communication partner.
void Disconnect () override
Disconnect from the communication partner (both sides will be disconnected).
Ptr< SimpleChannelInterface > GetCommunicationPartner () const
Get the ChannelInterface representing the other end of the communication channel.
Time GetPropagationDelay () const
Get the propagation delay of the channel when sending from this side of the channel.
int Send (Ptr< OpenGymDictContainer > data) override
Send data to the communication partner. This data transfer is delayed by the propagation delay this interface has.
void SetCommunicationPartner (Ptr< SimpleChannelInterface > communicationPartner)
Set the communication partner.
void SetPropagationDelay (Time delay)
Set the propagation delay of the channel when sending from this side of the channel.
Public Member Functions inherited from ChannelInterface
void AddRecvCallback (Callback< void, Ptr< OpenGymDictContainer >> callback)
Add a callback that is called when a message is received at the interface.
ConnectionStatus GetConnectionStatus () const
Get the connection status of the channel.
TracedCallback< Ptr< OpenGymDictContainer > > GetReceiveCallbacks () const
Get the trace source from which receive callbacks are executed.
void RemoveRecvCallback (Callback< void, Ptr< OpenGymDictContainer >> callback)
Remove a callback from the list of callbacks that are called when a message is received at the interface.
void SetConnectionStatus (ConnectionStatus status)
Set the connection status of the channel.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ChannelInterface
static TypeId GetTypeId ()
Get the type ID.
Detailed Description
A very basic implementation of a communication channel that allows the user to specify a delay for propagation. It must always be used in connection with another simple channel interface object.
Definition at line 16 of file simple-channel-interface.h.
Member Function Documentation
Connect()
ConnectionStatus SimpleChannelInterface::Connect (Ptr< ChannelInterface > otherInterface) override virtual
Establish a connection to the communication partner.
Parameters
otherInterface the interface representing the other end of the communication channel
Returns
the own connection status after the connection attempt (0 DISCONNECTED, 1 CONNECTING, 2 CONNECTED)
Implements ChannelInterface.
Definition at line 58 of file simple-channel-interface.cc.
References ChannelInterface::GetConnectionStatus(), SetCommunicationPartner(), and ChannelInterface::SetConnectionStatus().
GetCommunicationPartner()
Ptr< SimpleChannelInterface > SimpleChannelInterface::GetCommunicationPartner () const
Get the ChannelInterface representing the other end of the communication channel.
Returns
the communication partner.
Definition at line 163 of file simple-channel-interface.cc.
GetPropagationDelay()
Time SimpleChannelInterface::GetPropagationDelay () const
Get the propagation delay of the channel when sending from this side of the channel.
Returns
the propagation delay.
Definition at line 149 of file simple-channel-interface.cc.
GetTypeId()
TypeId SimpleChannelInterface::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 12 of file simple-channel-interface.cc.
Send()
int SimpleChannelInterface::Send (Ptr< OpenGymDictContainer > data) override virtual
Send data to the communication partner. This data transfer is delayed by the propagation delay this interface has.
Parameters
data data to send.
Returns
the number of bytes accepted for transmission if no error occurs, and -1 otherwise
Implements ChannelInterface.
Definition at line 32 of file simple-channel-interface.cc.
SetCommunicationPartner()
void SimpleChannelInterface::SetCommunicationPartner (Ptr< SimpleChannelInterface > communicationPartner)
Set the communication partner.
Parameters
communicationPartner the ChannelInterface representing the other end of the communication channel.
Definition at line 156 of file simple-channel-interface.cc.
Referenced by Connect().
SetPropagationDelay()
void SimpleChannelInterface::SetPropagationDelay (Time delay)
Set the propagation delay of the channel when sending from this side of the channel.
Parameters
delay the time the messages are delayed
Definition at line 142 of file simple-channel-interface.cc.
The documentation for this class was generated from the following files:
simple-channel-interface.h
simple-channel-interface.cc