defiance: ns3::CommunicationHelper Class Reference
ns3::CommunicationHelper Class Reference
defiance
Helper to setup communication between RlApplications.
#include "communication-helper.h"
Public Member Functions
CommunicationHelper (bool checkForSimpleInterfaces=true)
void AddCommunication (const std::vector< CommunicationPair > &communicationPairs)
Connect specified RlApplications.
void Configure ()
Calls Setup() on all RlApplications registered in this helper. Should be called after all RlApplications were set.
void DeleteCommunication (RlApplicationId localAppId, RlApplicationId remoteAppId, uint localInterfaceId=0, uint remoteInterfaceId=0)
Delete the communication connection between two RlApplications including the two interfaces.
Ptr< RlApplication > GetApp (RlApplicationId id)
Get the corresponding RlApplication for this RlApplicationId by looking it up in the right RlApplicationContainer.
void SetActionApps (RlApplicationContainer actionApps)
Set the ActionApps which are available in the scenario.
void SetAgentApps (RlApplicationContainer agentApps)
Set the AgentApps which are available in the scenario.
void SetIds ()
Assigns a unique RlApplicationId to all RlApplications registered in this helper. Should be called before communications are set, so that IDs can already be used there.
void SetObservationApps (RlApplicationContainer observationApps)
Set the ObservationApps which are available in the scenario.
void SetRewardApps (RlApplicationContainer rewardApps)
Set the RewardApps which are available in the scenario.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Protected Member Functions
std::pair< Ptr< ChannelInterface >, Ptr< ChannelInterface > > Connect (Ptr< RlApplication > clientApp, Ptr< RlApplication > serverApp, const CommunicationAttributes &attributes) const
Set up a communication relationship between two RlApplications over ChannelInterfaces.
Detailed Description
Helper to setup communication between RlApplications.
Definition at line 72 of file communication-helper.h.
Member Function Documentation
AddCommunication()
void ns3::CommunicationHelper::AddCommunication (const std::vector< CommunicationPair > & communicationPairs)
Connect specified RlApplications.
Parameters
communicationPairs includes a CommunicationPair for every connection to be made, clientId corresponds to ID of the first RlApplication, serverId to that of the second one.
Definition at line 108 of file communication-helper.cc.
References Connect(), and GetApp().
Connect()
std::pair< Ptr< ChannelInterface >, Ptr< ChannelInterface > > ns3::CommunicationHelper::Connect (Ptr< RlApplication > clientApp, Ptr< RlApplication > serverApp, const CommunicationAttributes & attributes) const protected
Set up a communication relationship between two RlApplications over ChannelInterfaces.
Parameters
clientApp first communication partner.
serverApp second communication partner (usually AgentApplication).
attributes reference to all attributes needed to set up the communication between clientApp and serverApp.
Returns
a pair consisting of the ChannelInterface for the clientApp and the ChannelInterface for the serverApp.
Definition at line 96 of file communication-helper.cc.
Referenced by AddCommunication().
DeleteCommunication()
void ns3::CommunicationHelper::DeleteCommunication (RlApplicationId localAppId, RlApplicationId remoteAppId, uint localInterfaceId = 0, uint remoteInterfaceId = 0)
Delete the communication connection between two RlApplications including the two interfaces.
Parameters
localAppId ID of the local RlApplication.
remoteAppId ID of the remote RlApplication connected to the local RlApplication.
localInterfaceId ID of the interface in the local RlApplication.
remoteInterfaceId ID of the interface in the remote RlApplication.
Definition at line 123 of file communication-helper.cc.
References GetApp().
GetApp()
Ptr< RlApplication > ns3::CommunicationHelper::GetApp (RlApplicationId id)
Get the corresponding RlApplication for this RlApplicationId by looking it up in the right RlApplicationContainer.
Parameters
id the ID to look up.
Returns
the corresponding RlApplication.
Definition at line 48 of file communication-helper.cc.
References ns3::RlApplicationContainer::Get().
Referenced by AddCommunication(), and DeleteCommunication().
GetTypeId()
TypeId ns3::CommunicationHelper::GetTypeId () static
Get the type ID.
Returns
the object TypeId.
Definition at line 9 of file communication-helper.cc.
SetActionApps()
void ns3::CommunicationHelper::SetActionApps (RlApplicationContainer actionApps)
Set the ActionApps which are available in the scenario.
Parameters
actionApps container of all ActionApps of the scenario. Currently, the order in the container is used to create the apps' IDs.
Definition at line 42 of file communication-helper.cc.
SetAgentApps()
void ns3::CommunicationHelper::SetAgentApps (RlApplicationContainer agentApps)
Set the AgentApps which are available in the scenario.
Parameters
agentApps container of all AgentApps of the scenario. Currently, the order in the container is used to create the apps' IDs.
Definition at line 36 of file communication-helper.cc.
SetIds()
void ns3::CommunicationHelper::SetIds ()
Assigns a unique RlApplicationId to all RlApplications registered in this helper. Should be called before communications are set, so that IDs can already be used there.
This assigns the IDs in increasing order starting at 0. To customize, override this function.
Definition at line 135 of file communication-helper.cc.
References ns3::RlApplicationContainer::Get().
SetObservationApps()
void ns3::CommunicationHelper::SetObservationApps (RlApplicationContainer observationApps)
Set the ObservationApps which are available in the scenario.
Parameters
observationApps container of all ObservationApps of the scenario. Currently, the order in the container is used to create the apps' IDs.
Definition at line 24 of file communication-helper.cc.
SetRewardApps()
void ns3::CommunicationHelper::SetRewardApps (RlApplicationContainer rewardApps)
Set the RewardApps which are available in the scenario.
Parameters
rewardApps container of all RewardApps of the scenario. Currently, the order in the container is used to create the apps' IDs.
Definition at line 30 of file communication-helper.cc.
The documentation for this class was generated from the following files:
communication-helper.h
communication-helper.cc