defiance: ns3::TopologyCreator Class Reference
ns3::TopologyCreator Class Reference
defiance
This class helps to create realistic scenarios with base stations from OSM and moving user equipment from SUMO.
#include "topology-creator.h"
Public Member Functions
NodeContainer CreateUserEquipment (uint32_t numUe=3, uint32_t seed=42, std::string location="")
Create a NodeContainer containing User Equipment walking around on the streets of the location.
NodeContainer GetBaseStations (float centerX, float centerY, float sizeX, float sizeY)
Create a NodeContainer with the base stations at the specified location.
NodeContainer GetBaseStations (std::string location="")
Search for base station of scenario and already created scenarios. Leave empty to get base stations of the last set scenario.
std::string GetDirectoryName (float centerX, float centerY, float sizeX, float sizeY)
Get the name of the directory containing config and trace files.
std::string SetScenario (float centerX, float centerY, float sizeX, float sizeY)
Set the location of the scenario to a specific area. Creates the necessary config files. These config files can be used for the generation of UEs.
std::string SetScenario (std::string location="Babelsberg")
Set the location of the scenario to one of the default scenarios.
std::string SetScenario (uint32_t numBs=5, uint32_t seed=42, uint32_t minDensity=20, uint32_t maxDensity=25)
Set the location of the scenario pseudo-randomly with a specific number of base stations.
Detailed Description
This class helps to create realistic scenarios with base stations from OSM and moving user equipment from SUMO.
It provides some default scenarios for you to use. You can also create your scenario by specifying a specific location center and size. Another option is to specify the desired number of base stations and let the class find a pseudo-random location for you (for reproducibility).
Definition at line 23 of file topology-creator.h.
Member Function Documentation
CreateUserEquipment()
NodeContainer ns3::TopologyCreator::CreateUserEquipment (uint32_t numUe = 3, uint32_t seed = 42, std::string location = "")
Create a NodeContainer containing User Equipment walking around on the streets of the location.
Parameters
numUe the number of user equipment to create.
seed the seed for pseudo-randomization.
location the name of the scenario as a string.
Returns
a NodeContainer containing the user equipment nodes. They internally have a mobility model and will walk around when starting the simulation.
Definition at line 164 of file topology-creator.cc.
References GetDirectoryName().
GetBaseStations() [1/2]
NodeContainer ns3::TopologyCreator::GetBaseStations (float centerX, float centerY, float sizeX, float sizeY)
Create a NodeContainer with the base stations at the specified location.
Parameters
centerX the x-coordinate of the center of the scenario.
centerY the y-coordinate of the center of the scenario.
sizeX the x-size of the scenario.
sizeY the y-size of the scenario.
Returns
the according NodeContainer.
Todo:
Check whether the location is valid.
Definition at line 124 of file topology-creator.cc.
References GetDirectoryName().
Referenced by GetBaseStations(), and SetScenario().
GetBaseStations() [2/2]
NodeContainer ns3::TopologyCreator::GetBaseStations (std::string location = "")
Search for base station of scenario and already created scenarios. Leave empty to get base stations of the last set scenario.
Parameters
location the name of the scenario as a string.
Returns
according NodeContainer if string is found, else empty NodeContainer.
Definition at line 145 of file topology-creator.cc.
References GetBaseStations().
GetDirectoryName()
std::string ns3::TopologyCreator::GetDirectoryName (float centerX, float centerY, float sizeX, float sizeY)
Get the name of the directory containing config and trace files.
Parameters
centerX the x-coordinate of the center of the scenario.
centerY the y-coordinate of the center of the scenario.
sizeX the x-size of the scenario.
sizeY the y-size of the scenario.
Returns
the name of the directory containing the scenario files.
Definition at line 55 of file topology-creator.cc.
Referenced by CreateUserEquipment(), GetBaseStations(), and SetScenario().
SetScenario() [1/3]
std::string ns3::TopologyCreator::SetScenario (float centerX, float centerY, float sizeX, float sizeY)
Set the location of the scenario to a specific area. Creates the necessary config files. These config files can be used for the generation of UEs.
Parameters
centerX the x-coordinate of the center of the scenario.
centerY the y-coordinate of the center of the scenario.
sizeX the x-size of the scenario.
sizeY the y-size of the scenario.
Returns
the name of the scenario. This name is also the name of the directory containing the scenario files.
Definition at line 65 of file topology-creator.cc.
References GetBaseStations(), and GetDirectoryName().
Referenced by SetScenario().
SetScenario() [2/3]
std::string ns3::TopologyCreator::SetScenario (std::string location = "Babelsberg")
Set the location of the scenario to one of the default scenarios.
Parameters
location the name of the scenario. Currently supported are "Babelsberg" with 29 BS, "Babelsmall" with 21 BS, "Berlin" with 14 BS, and "Berlinbig" with 32 BS.
Returns
the name of the scenario. This name is also the name of the directory containing the scenario files.
Definition at line 86 of file topology-creator.cc.
References SetScenario().
SetScenario() [3/3]
std::string ns3::TopologyCreator::SetScenario (uint32_t numBs = 5, uint32_t seed = 42, uint32_t minDensity = 20, uint32_t maxDensity = 25)
Set the location of the scenario pseudo-randomly with a specific number of base stations.
Parameters
numBs the number of desired base stations in the scenario.
seed the seed for pseudo-random location sampling.
minDensity the minimum density of base stations in the scenario.
maxDensity the maximum density of base stations in the scenario.
Returns
the name of the scenario. This name is also the name of the directory containing the scenario files.
Definition at line 102 of file topology-creator.cc.
References SetScenario().
The documentation for this class was generated from the following files:
topology-creator.h
topology-creator.cc