defiance: ns3::RlApplication Class Reference
ns3::RlApplication Class Reference
defiance
This class embodies the core functionality of all RL applications.
#include "rl-application.h"
Public Member Functions
uint AddInterface (RlApplicationId applicationId, Ptr< ChannelInterface > interface)
Add a new interface to this app.
void DeleteInterface (RlApplicationId applicationId, uint interfaceId)
Ipv4Address GetDefaultAddress ()
Retrieve default IP address for new interfaces.
RlApplicationId GetId ()
Retrieve the RlApplicationId of a specific RL application.
void SetDefaultAddress (Ipv4Address address)
Set default IP address that is used for new interfaces.
void SetId (RlApplicationId id)
Set ID that is unique among all RL applications.
virtual void Setup ()
Called after configuration is finished.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Protected Member Functions
virtual void Send (Ptr< OpenGymDictContainer > data, const InterfaceMap &interfaces)
Send data to the specified interfaces if the application is currently running. This method is not atomic. It might happen that data is only sent to some RlApplications if m_running changes to false.
virtual void Send (Ptr< OpenGymDictContainer > data, const std::map< uint, Ptr< ChannelInterface >> &interfaces)
Send data to the specified interfaces if the application is currently running.
virtual void Send (Ptr< OpenGymDictContainer > data, const std::vector< Ptr< ChannelInterface >> &interfaces)
Send data to the specified interfaces if the application is currently running.
void StartApplication () override
Set the application to running mode so that observations can be sent.
void StopApplication () override
Stop running mode so that observations cannot be sent anymore.
Protected Attributes
bool m_running
Detailed Description
This class embodies the core functionality of all RL applications.
Definition at line 46 of file rl-application.h.
Member Function Documentation
AddInterface()
uint ns3::RlApplication::AddInterface (RlApplicationId applicationId, Ptr< ChannelInterface > interface)
Add a new interface to this app.
Parameters
applicationId ID identifying the remote application sending and receiving through the interface.
interface interface for this connection to the app.
Returns
the index of the newly added interface in the list of interfaces connected to the same remote application.
Definition at line 125 of file rl-application.cc.
References ns3::RlApplicationId::applicationId, and ns3::RlApplicationId::applicationType.
DeleteInterface()
void ns3::RlApplication::DeleteInterface (RlApplicationId applicationId, uint interfaceId)
Delete an interface of this app.
Parameters
applicationId to identify the remote application sending and receiving through the interface.
interfaceId index of the interface among all interfaces which are connected to the specified RlApplication and registered in this RlApplication.
Definition at line 168 of file rl-application.cc.
References ns3::RlApplicationId::applicationId, and ns3::RlApplicationId::applicationType.
GetDefaultAddress()
Ipv4Address ns3::RlApplication::GetDefaultAddress ()
Retrieve default IP address for new interfaces.
Returns
default address.
Definition at line 73 of file rl-application.cc.
GetId()
RlApplicationId ns3::RlApplication::GetId ()
Retrieve the RlApplicationId of a specific RL application.
Returns
the desired RlApplicationId.
Definition at line 61 of file rl-application.cc.
Referenced by ns3::AgentApplication::InferAction(), and ns3::AgentApplication::Setup().
GetTypeId()
TypeId ns3::RlApplication::GetTypeId () static
Get the type ID.
Returns
the object TypeId.
Definition at line 26 of file rl-application.cc.
Send() [1/3]
void ns3::RlApplication::Send (Ptr< OpenGymDictContainer > data, const InterfaceMap & interfaces) protected virtual
Send data to the specified interfaces if the application is currently running. This method is not atomic. It might happen that data is only sent to some RlApplications if m_running changes to false.
Parameters
data the data to send.
interfaces interfaces over which the data is sent.
Definition at line 215 of file rl-application.cc.
References Send().
Send() [2/3]
void ns3::RlApplication::Send (Ptr< OpenGymDictContainer > data, const std::map< uint, Ptr< ChannelInterface >> & interfaces) protected virtual
Send data to the specified interfaces if the application is currently running.
Parameters
data the data to send.
interfaces interfaces over which the data is sent.
Definition at line 201 of file rl-application.cc.
References m_running.
Send() [3/3]
void ns3::RlApplication::Send (Ptr< OpenGymDictContainer > data, const std::vector< Ptr< ChannelInterface >> & interfaces) protected virtual
Send data to the specified interfaces if the application is currently running.
Parameters
data the data to send.
interfaces interfaces over which the data is sent.
Definition at line 187 of file rl-application.cc.
References m_running.
Referenced by Send(), ns3::DataCollectorApplication::Send(), ns3::AgentApplication::SendAction(), and ns3::AgentApplication::SendToAgent().
SetDefaultAddress()
void ns3::RlApplication::SetDefaultAddress (Ipv4Address address)
Set default IP address that is used for new interfaces.
Parameters
address default address for new interfaces.
Definition at line 67 of file rl-application.cc.
Referenced by Setup().
SetId()
void ns3::RlApplication::SetId (RlApplicationId id)
Set ID that is unique among all RL applications.
Parameters
id unique ID among RLApplications.
Definition at line 55 of file rl-application.cc.
Member Data Documentation
m_running
bool ns3::RlApplication::m_running protected
If true, messages to other RlApplications can be sent, if false, Send methods throw all messages away
Definition at line 142 of file rl-application.h.
Referenced by Send(), StartApplication(), and StopApplication().
The documentation for this class was generated from the following files:
rl-application.h
rl-application.cc