defiance: ns3::AgentApplication Class Reference
ns3::AgentApplication Class Reference abstract
defiance
This application is installed on a node on which the RL agent is to be placed in the network.
#include "agent-application.h"
Public Member Functions
uint AddActionInterface (uint32_t remoteAppId, Ptr< ChannelInterface > interface) override
Add a ChannelInterface to this AgentApplication over which it can send actions to an ActionApplication.
uint AddAgentInterface (uint32_t remoteAppId, Ptr< ChannelInterface > interface) override
Add a ChannelInterface to this AgentApplication over which it can communicate with another AgentApplication.
uint AddObservationInterface (uint32_t remoteAppId, Ptr< ChannelInterface > interface) override
Add a ChannelInterface to this AgentApplication over which observations from an ObservationApplication can be received.
uint AddRewardInterface (uint32_t remoteAppId, Ptr< ChannelInterface > interface) override
Add a ChannelInterface to this AgentApplication over which rewards from a RewardApplication can be received.
void DeleteActionInterface (uint32_t remoteAppId, uint interfaceId) override
Delete a ChannelInterface that is currently connected to an ActionApplication.
void DeleteAgentInterface (uint32_t remoteAppId, uint interfaceId) override
Delete a ChannelInterface that is currently connected to a remote AgentApplication.
void DeleteObservationInterface (uint32_t remoteAppId, uint interfaceId) override
Delete a ChannelInterface that is currently connected to an ObservationApplication.
void DeleteRewardInterface (uint32_t remoteAppId, uint interfaceId) override
Delete a ChannelInterface that is currently connected to a RewardApplication.
void SendAction (Ptr< OpenGymDictContainer > action)
Send an action to all connected ActionApplications (via all according ChannelInterfaces). This method is not atomic. It might happen that the action is only sent to some ActionApplications if m_running changes to false.
void SendAction (Ptr< OpenGymDictContainer > action, uint32_t appId)
Send an action to the specified ActionApplication via all according ChannelInterfaces.
void SendAction (Ptr< OpenGymDictContainer > action, uint32_t appId, uint32_t interfaceId)
Send an action to the specified ActionApplication via the given ChannelInterface.
void SendToAgent (Ptr< OpenGymDictContainer > data)
Send a message to all connected AgentApplications (via all according ChannelInterfaces). This method is not atomic. It might happen that the message is only sent to some AgentApplications if m_running changes to false.
void SendToAgent (Ptr< OpenGymDictContainer > data, uint32_t appId)
Send a message to the specified AgentApplication via all according ChannelInterfaces.
void SendToAgent (Ptr< OpenGymDictContainer > data, uint32_t appId, uint32_t interfaceId)
Send a message to the specified AgentApplication via the given ChannelInterface.
void Setup () override
Initialize the data structures for storing observations resp. rewards and the observation and action spaces. Can be overridden if needed.
Public Member Functions inherited from ns3::RlApplication
uint AddInterface (RlApplicationId applicationId, Ptr< ChannelInterface > interface)
Add a new interface to this app.
void DeleteInterface (RlApplicationId applicationId, uint interfaceId)
Ipv4Address GetDefaultAddress ()
Retrieve default IP address for new interfaces.
RlApplicationId GetId ()
Retrieve the RlApplicationId of a specific RL application.
void SetDefaultAddress (Ipv4Address address)
Set default IP address that is used for new interfaces.
void SetId (RlApplicationId id)
Set ID that is unique among all RL applications.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::RlApplication
static TypeId GetTypeId ()
Get the type ID.
Protected Member Functions
void InferAction ()
void InferAction (uint remoteAppId)
virtual void OnRecvFromAgent (uint remoteAppId, Ptr< OpenGymDictContainer > payload)
Called when a message is received from an agent.
virtual void OnRecvObs (uint remoteAppId)=0
Called when an observation was received. The observation was already stored in m_obsDataStruct. Once there are enough observations, InferAction() should be called to begin the inference cycle.
virtual void OnRecvReward (uint remoteAppId)=0
Called when a reward was received. The reward was already stored in m_rewardDataStruct.
Protected Member Functions inherited from ns3::RlApplication
virtual void Send (Ptr< OpenGymDictContainer > data, const InterfaceMap &interfaces)
Send data to the specified interfaces if the application is currently running. This method is not atomic. It might happen that data is only sent to some RlApplications if m_running changes to false.
virtual void Send (Ptr< OpenGymDictContainer > data, const std::map< uint, Ptr< ChannelInterface >> &interfaces)
Send data to the specified interfaces if the application is currently running.
virtual void Send (Ptr< OpenGymDictContainer > data, const std::vector< Ptr< ChannelInterface >> &interfaces)
Send data to the specified interfaces if the application is currently running.
void StartApplication () override
Set the application to running mode so that observations can be sent.
void StopApplication () override
Stop running mode so that observations cannot be sent anymore.
Protected Attributes
InterfaceMap m_actionInterfaces
Interfaces connecting this AgentApplication to ActionApplications.
InterfaceMap m_agentInterfaces
uint m_maxObservationHistoryLength
uint m_maxRewardHistoryLength
maximum length of the history of each reward deque to store
HistoryContainer m_obsDataStruct
a data structure in which received observations are stored
Ptr< OpenGymDataContainer > m_observation
the current observation which is used in InferAction()
InterfaceMap m_observationInterfaces
bool m_obsTimestamping
enable ns3 timestamps for observations
float m_reward
the current reward which is used in InferAction()
HistoryContainer m_rewardDataStruct
a data structure in which received rewards are stored
InterfaceMap m_rewardInterfaces
bool m_rewardTimestamping
enable ns3 timestamps for rewards
Protected Attributes inherited from ns3::RlApplication
bool m_running
Detailed Description
This application is installed on a node on which the RL agent is to be placed in the network.
Before the AgentApplication is started Setup() should be called to initiate necessary configurations. In order to receive observations or rewards from other applications, the AgentApplication needs to add the according interfaces with AddObservationInterface(), AddRewardInterface(), AddActionInterface() or AddAgentInterface(). When an observation or a reward is received, the AgentApplication stores it in a data structure and calls OnRecvObs() resp. OnRecvReward() with the ID of the interface the observation or reward was received from. The AgentApplication needs to implement OnRecvObs() and OnRecvReward() to handle received observations and rewards.
Definition at line 24 of file agent-application.h.
Member Function Documentation
AddActionInterface()
uint ns3::AgentApplication::AddActionInterface (uint32_t remoteAppId, Ptr< ChannelInterface > interface) override virtual
Add a ChannelInterface to this AgentApplication over which it can send actions to an ActionApplication.
Parameters
remoteAppId the ID of the ActionApplication the interface is connected to.
interface the interface for sending actions to specific ActionApplication.
Returns
the ID of the newly added interface among all interfaces of this AgentApplication which are connected to the specified ActionApplication.
Reimplemented from ns3::RlApplication.
Definition at line 143 of file agent-application.cc.
References m_actionInterfaces.
AddAgentInterface()
uint ns3::AgentApplication::AddAgentInterface (uint32_t remoteAppId, Ptr< ChannelInterface > interface) override virtual
Add a ChannelInterface to this AgentApplication over which it can communicate with another AgentApplication.
Parameters
remoteAppId the ID of the AgentApplication the interface is connected to.
interface the interface for communicating with specific AgentApplication.
Returns
the ID of the newly added interface among all interfaces of this AgentApplication which are connected to the specified (remote) AgentApplication.
Reimplemented from ns3::RlApplication.
Definition at line 105 of file agent-application.cc.
References OnRecvFromAgent().
AddObservationInterface()
uint ns3::AgentApplication::AddObservationInterface (uint32_t remoteAppId, Ptr< ChannelInterface > interface) override virtual
Add a ChannelInterface to this AgentApplication over which observations from an ObservationApplication can be received.
Parameters
remoteAppId the ID of the ObservationApplication the interface is connected to.
interface the interface for receiving observations from specific ObservationApplication.
Returns
the ID of the newly added interface among all interfaces of this AgentApplication which are connected to the specified ObservationApplication.
Reimplemented from ns3::RlApplication.
Definition at line 85 of file agent-application.cc.
AddRewardInterface()
uint ns3::AgentApplication::AddRewardInterface (uint32_t remoteAppId, Ptr< ChannelInterface > interface) override virtual
Add a ChannelInterface to this AgentApplication over which rewards from a RewardApplication can be received.
Parameters
remoteAppId the ID of the RewardApplication the interface is connected to.
interface the interface for receiving rewards from specific RewardApplication.
Returns
the ID of the newly added interface among all interfaces of this AgentApplication which are connected to the specified RewardApplication.
Reimplemented from ns3::RlApplication.
Definition at line 124 of file agent-application.cc.
DeleteActionInterface()
void ns3::AgentApplication::DeleteActionInterface (uint32_t remoteAppId, uint interfaceId) override virtual
Delete a ChannelInterface that is currently connected to an ActionApplication.
Parameters
remoteAppId the ID of the ActionApplication the interface is connected to.
interfaceId the ID of the ChannelInterface to delete. This is the ID among all interfaces of this AgentApplication which are connected to the specified ActionApplication.
Reimplemented from ns3::RlApplication.
Definition at line 188 of file agent-application.cc.
References m_actionInterfaces.
DeleteAgentInterface()
void ns3::AgentApplication::DeleteAgentInterface (uint32_t remoteAppId, uint interfaceId) override virtual
Delete a ChannelInterface that is currently connected to a remote AgentApplication.
Parameters
remoteAppId the ID of the AgentApplication the interface is connected to.
interfaceId the ID of the ChannelInterface to delete. This is the ID among all interfaces of this AgentApplication which are connected to the specified AgentApplication.
Reimplemented from ns3::RlApplication.
Definition at line 179 of file agent-application.cc.
DeleteObservationInterface()
void ns3::AgentApplication::DeleteObservationInterface (uint32_t remoteAppId, uint interfaceId) override virtual
Delete a ChannelInterface that is currently connected to an ObservationApplication.
Parameters
remoteAppId the ID of the ObservationApplication the interface is connected to.
interfaceId the ID of the ChannelInterface to delete. This is the ID among all interfaces of this AgentApplication which are connected to the specified ObservationApplication.
Reimplemented from ns3::RlApplication.
Definition at line 161 of file agent-application.cc.
DeleteRewardInterface()
void ns3::AgentApplication::DeleteRewardInterface (uint32_t remoteAppId, uint interfaceId) override virtual
Delete a ChannelInterface that is currently connected to a RewardApplication.
Parameters
remoteAppId the ID of the RewardApplication the interface is connected to.
interfaceId the ID of the ChannelInterface to delete. This is the ID among all interfaces of this AgentApplication which are connected to the specified RewardApplication.
Reimplemented from ns3::RlApplication.
Definition at line 170 of file agent-application.cc.
GetTypeId()
TypeId ns3::AgentApplication::GetTypeId () static
Get the type ID.
Returns
the object TypeId.
Definition at line 20 of file agent-application.cc.
References m_maxObservationHistoryLength, m_maxRewardHistoryLength, m_obsTimestamping, and m_rewardTimestamping.
InferAction() [1/2]
void ns3::AgentApplication::InferAction () protected
Send observation and reward to the python agent and infer an action. This action is passed to SendAction() for forwarding. It uses m_observation and m_reward.
Definition at line 263 of file agent-application.cc.
References ns3::RlApplication::GetId(), m_observation, and m_reward.
InferAction() [2/2]
void ns3::AgentApplication::InferAction (uint remoteAppId) protected
Send observation and reward to the python agent and infer an action. This action is passed to SendAction() for forwarding. It uses m_observation and m_reward.
Parameters
remoteAppId ID of the ActionApplication to which the action shall be passed
Definition at line 277 of file agent-application.cc.
References ns3::RlApplication::GetId(), m_observation, and m_reward.
OnRecvFromAgent()
void ns3::AgentApplication::OnRecvFromAgent (uint remoteAppId, Ptr< OpenGymDictContainer > payload) protected virtual
Called when a message is received from an agent.
Parameters
remoteAppId ID of the RewardApplication from which the reward was received.
Definition at line 58 of file agent-application.cc.
Referenced by AddAgentInterface().
OnRecvObs()
virtual void ns3::AgentApplication::OnRecvObs (uint remoteAppId) protected pure virtual
Called when an observation was received. The observation was already stored in m_obsDataStruct. Once there are enough observations, InferAction() should be called to begin the inference cycle.
Parameters
remoteAppId ID of the RewardApplication from which the reward was received.
Implemented in ns3::TestAgentApp.
OnRecvReward()
virtual void ns3::AgentApplication::OnRecvReward (uint remoteAppId) protected pure virtual
Called when a reward was received. The reward was already stored in m_rewardDataStruct.
Parameters
remoteAppId ID of the RewardApplication from which the reward was received.
Implemented in ns3::TestAgentApp.
SendAction() [1/3]
void ns3::AgentApplication::SendAction (Ptr< OpenGymDictContainer > action)
Send an action to all connected ActionApplications (via all according ChannelInterfaces). This method is not atomic. It might happen that the action is only sent to some ActionApplications if m_running changes to false.
Parameters
action the action to send.
Definition at line 256 of file agent-application.cc.
References m_actionInterfaces, and ns3::RlApplication::Send().
SendAction() [2/3]
void ns3::AgentApplication::SendAction (Ptr< OpenGymDictContainer > action, uint32_t appId)
Send an action to the specified ActionApplication via all according ChannelInterfaces.
Parameters
action the action to send.
appId ID of the ActionApplication to which the action is sent.
Definition at line 249 of file agent-application.cc.
References m_actionInterfaces, and ns3::RlApplication::Send().
SendAction() [3/3]
void ns3::AgentApplication::SendAction (Ptr< OpenGymDictContainer > action, uint32_t appId, uint32_t interfaceId)
Send an action to the specified ActionApplication via the given ChannelInterface.
Parameters
action the action to send.
appId the ID of the ActionApplication to which the action is sent.
interfaceId the ID of the interface to use. This is the ID among all interfaces of this AgentApplication which are connected to the specified ActionApplication.
Definition at line 236 of file agent-application.cc.
References m_actionInterfaces, and ns3::RlApplication::Send().
SendToAgent() [1/3]
void ns3::AgentApplication::SendToAgent (Ptr< OpenGymDictContainer > data)
Send a message to all connected AgentApplications (via all according ChannelInterfaces). This method is not atomic. It might happen that the message is only sent to some AgentApplications if m_running changes to false.
Parameters
data the message to send.
Definition at line 229 of file agent-application.cc.
References ns3::RlApplication::Send().
SendToAgent() [2/3]
void ns3::AgentApplication::SendToAgent (Ptr< OpenGymDictContainer > data, uint32_t appId)
Send a message to the specified AgentApplication via all according ChannelInterfaces.
Parameters
data the message to send.
appId the ID of the AgentApplication to which the message is sent.
Definition at line 222 of file agent-application.cc.
References ns3::RlApplication::Send().
SendToAgent() [3/3]
void ns3::AgentApplication::SendToAgent (Ptr< OpenGymDictContainer > data, uint32_t appId, uint32_t interfaceId)
Send a message to the specified AgentApplication via the given ChannelInterface.
Parameters
data the message to send.
appId the ID of the AgentApplication to which the message is sent.
interfaceId the ID of the interface to use. This is the ID among all interfaces of this AgentApplication which are connected to the specified (receiving) AgentApplication.
Definition at line 209 of file agent-application.cc.
References ns3::RlApplication::Send().
Member Data Documentation
m_maxObservationHistoryLength
uint ns3::AgentApplication::m_maxObservationHistoryLength protected
maximum length of the history of each observation deque to store
Definition at line 170 of file agent-application.h.
Referenced by GetTypeId(), and Setup().
The documentation for this class was generated from the following files:
agent-application.h
agent-application.cc