defiance: ns3::RlApplicationHelper Class Reference
ns3::RlApplicationHelper Class Reference
defiance
A helper to make it easier to instantiate an RlApplication on a set of nodes.
#include "rl-application-helper.h"
Public Member Functions
RlApplicationHelper (const std::string &typeId)
RlApplicationHelper (TypeId typeId)
RlApplicationContainer Install (const std::string &nodeName)
RlApplicationContainer Install (NodeContainer c)
RlApplicationContainer Install (Ptr< Node > node)
void SetAttribute (const std::string &name, const AttributeValue &value)
void SetTypeId (const std::string &typeId)
void SetTypeId (TypeId typeId)
Protected Member Functions
virtual Ptr< RlApplication > DoInstall (Ptr< Node > node)
Protected Attributes
ObjectFactory m_factory
Object factory.
Detailed Description
A helper to make it easier to instantiate an RlApplication on a set of nodes.
Definition at line 20 of file rl-application-helper.h.
Constructor & Destructor Documentation
RlApplicationHelper() [1/2]
ns3::RlApplicationHelper::RlApplicationHelper (TypeId typeId) explicit
Create an RlApplication of a given type ID
Parameters
typeId the type ID.
Definition at line 10 of file rl-application-helper.cc.
References SetTypeId().
RlApplicationHelper() [2/2]
ns3::RlApplicationHelper::RlApplicationHelper (const std::string & typeId) explicit
Create an RlApplication of a given type ID
Parameters
typeId the type ID expressed as a string.
Definition at line 15 of file rl-application-helper.cc.
References SetTypeId().
Member Function Documentation
DoInstall()
Ptr< RlApplication > ns3::RlApplicationHelper::DoInstall (Ptr< Node > node) protected virtual
Install an RlApplication on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an application will be installed.
Returns
Ptr to the Application installed.
Definition at line 64 of file rl-application-helper.cc.
References m_factory.
Referenced by Install().
Install() [1/3]
RlApplicationContainer ns3::RlApplicationHelper::Install (const std::string & nodeName)
Install an RlApplication on the node configured with all the attributes set with SetAttribute.
Parameters
nodeName The node on which an application will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 45 of file rl-application-helper.cc.
References DoInstall().
Install() [2/3]
RlApplicationContainer ns3::RlApplicationHelper::Install (NodeContainer c)
Install an RlApplication on each node of the input container configured with all the attributes set with SetAttribute.
Parameters
c NodeContainer of the set of nodes on which an application will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 53 of file rl-application-helper.cc.
References DoInstall().
Install() [3/3]
RlApplicationContainer ns3::RlApplicationHelper::Install (Ptr< Node > node)
Install an RlApplication on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an application will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 39 of file rl-application-helper.cc.
References DoInstall().
SetAttribute()
void ns3::RlApplicationHelper::SetAttribute (const std::string & name, const AttributeValue & value)
Helper function used to set the underlying application attributes.
Parameters
name the name of the application attribute to set
value the value of the application attribute to set
Definition at line 33 of file rl-application-helper.cc.
References m_factory.
SetTypeId() [1/2]
void ns3::RlApplicationHelper::SetTypeId (const std::string & typeId)
Allow the helper to be repurposed for another RlApplication type
Parameters
typeId the type ID expressed as a string.
Definition at line 27 of file rl-application-helper.cc.
References m_factory.
SetTypeId() [2/2]
void ns3::RlApplicationHelper::SetTypeId (TypeId typeId)
Allow the helper to be repurposed for another RlApplication type
Parameters
typeId the type ID.
Definition at line 21 of file rl-application-helper.cc.
References m_factory.
Referenced by RlApplicationHelper().
The documentation for this class was generated from the following files:
rl-application-helper.h
rl-application-helper.cc