defiance: ns3::RlApplicationContainer Class Reference
ns3::RlApplicationContainer Class Reference
defiance
Instances of this class hold a vector of ns3::Application pointers.
#include "rl-application-container.h"
Public Member Functions
RlApplicationContainer ()
RlApplicationContainer (ApplicationContainer c)
Create an RlApplicationContainer from a plain ApplicationContainer.
RlApplicationContainer (Ptr< Application > application)
RlApplicationContainer (std::string name)
Ptr< RlApplication > Get (uint32_t index) const
Get the RlApplication stored in this container at a given index.
RlApplicationId GetId (uint32_t index) const
Get the RlApplicationId of the RlApplication stored in this container at a given index.
Detailed Description
Instances of this class hold a vector of ns3::Application pointers.
Typically ns-3 Applications are installed on nodes using an Application helper. The helper Install method takes a NodeContainer which holds some number of Ptr<Node>. For each of the Nodes in the NodeContainer the helper will instantiate an application, install it in a node and add a Ptr<Application> to that application into a Container for use by the caller. This is that container used to hold the Ptr<Application> which are instantiated by the Application helper.
Definition at line 22 of file rl-application-container.h.
Constructor & Destructor Documentation
RlApplicationContainer() [1/3]
ns3::RlApplicationContainer::RlApplicationContainer () inline
Create an empty RlApplicationContainer.
Definition at line 28 of file rl-application-container.h.
RlApplicationContainer() [2/3]
ns3::RlApplicationContainer::RlApplicationContainer (Ptr< Application > application) inline
Create an RlApplicationContainer with exactly one application which has been previously instantiated. The single application is specified by a smart pointer.
Parameters
application The Ptr<Application> to add to the container. If you want to use the application as an RlApplication, you should add it to the container as such.
Definition at line 48 of file rl-application-container.h.
RlApplicationContainer() [3/3]
ns3::RlApplicationContainer::RlApplicationContainer (std::string name) inline
Create an RlApplicationContainer with exactly one application which has been previously instantiated and assigned a name using the Object Name Service. This Application is then specified by its assigned name.
Parameters
name The name of the Application Object to add to the container.
Definition at line 60 of file rl-application-container.h.
Member Function Documentation
Get()
Ptr< RlApplication > ns3::RlApplicationContainer::Get (uint32_t index) const
Get the RlApplication stored in this container at a given index.
Parameters
index the index of the requested RlApplication pointer.
Returns
the requested RlApplication pointer.
Definition at line 9 of file rl-application-container.cc.
Referenced by ns3::CommunicationHelper::Configure(), ns3::CommunicationHelper::GetApp(), GetId(), and ns3::CommunicationHelper::SetIds().
GetId()
RlApplicationId ns3::RlApplicationContainer::GetId (uint32_t index) const
Get the RlApplicationId of the RlApplication stored in this container at a given index.
Parameters
index the index of the requested RlApplication.
Returns
the RlApplicationId of the requested RlApplication.
Definition at line 15 of file rl-application-container.cc.
References Get().
The documentation for this class was generated from the following files:
rl-application-container.h
rl-application-container.cc