defiance: ns3::MobComEnv Class Reference
ns3::MobComEnv Class Reference abstract
defiance
Public Member Functions
MobComEnv (Time simulationDuration, Time notificationRate, Time notificationStart)
Constructor for the MobComEnv class.
void DoDispose () override
bool ExecuteActions (Ptr< OpenGymDataContainer > action) override=0
Ptr< OpenGymSpace > GetActionSpace () override=0
DeviceManager * GetDeviceManager ()
Ptr< EpcHelper > GetEpcHelper ()
std::map< std::string, std::string > GetExtraInfo () override
bool GetGameOver () override
Always return false here, as mobile environments are continous. This becomes the terminated field in Gymnasium. Use a TimeLimit object to truncate the environment after a given amount of steps.
Ptr< LteHelper > GetLteHelper ()
Ptr< OpenGymDataContainer > GetObservation () override=0
Ptr< OpenGymSpace > GetObservationSpace () override=0
float GetReward () override=0
Time GetSimulationDuration ()
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Protected Member Functions
virtual void AddTraffic ()=0
Overwrite to add internet traffic to the scenario. Include 1. Routing and IPs, 2. Attaching UEs and eNbs, and 3. Registering applications.
void AttachUEsToEnbs ()
Attach user equipment to base stations. By default, each UE is attached to the closest base station.
virtual void CreateTopology ()=0
Fill containers for UEs and base stations. The specific topology has to be specified in the child class.
virtual void RegisterCallbacks ()
Register the necessary callbacks for tracing.
void ScheduleNotificationEvents ()
Schedule the Notify() events according to m_notificationRate.
virtual void SetScenarioAttributes ()
Override this method in the child class to set global attributes, or attributes specific to the LteHelper or EpcHelper. In case you do not override this method, default values will be used. Example for setting the Propagation Model: GetLteHelper()->SetPathlossModelType(TypeId::LookupByName("ns3::RangePropagationLossModel")); GetLteHelper()->SetPathlossModelAttribute("MaxRange", DoubleValue(2000));.
virtual void SetupScenario ()
Template method for scenario creation. Customize it by overriding SetScenarioAttributes(), ScheduleNotificationEvents(), CreateTopology(), AddTraffic() and RegisterCallbacks().
Protected Attributes
DeviceManager * m_deviceManager
Ptr< EpcHelper > m_epcHelper
Ptr< LteHelper > m_lteHelper
const Time m_notificationRate
const Time m_notificationStart
const Time m_simulationDuration
Maximum duration of the simulation Default = Seconds(200);.
Detailed Description
Definition at line 23 of file base-environment.h.
Constructor & Destructor Documentation
MobComEnv()
ns3::MobComEnv::MobComEnv (Time simulationDuration, Time notificationRate, Time notificationStart)
Constructor for the MobComEnv class.
Parameters
simulationDuration the maximum of the simulation.
notificationRate the rate at which Notify() should be called to send the observations to python and get the agent's actions.
notificationStart the time at which the first notification should be sent.
Definition at line 22 of file base-environment.cc.
Member Function Documentation
AddTraffic()
virtual void ns3::MobComEnv::AddTraffic () protected pure virtual
Overwrite to add internet traffic to the scenario. Include 1. Routing and IPs, 2. Attaching UEs and eNbs, and 3. Registering applications.
See also
static-environment.cc
Implemented in ns3::StaticMobComEnv, and ns3::PowerControlMobComEnv.
Referenced by ns3::PowerControlMobComEnv::MobComEnv().
GetDeviceManager()
DeviceManager * ns3::MobComEnv::GetDeviceManager ()
Returns
a pointer to the device manager.
Definition at line 91 of file base-environment.cc.
Referenced by ns3::PowerControlMobComEnv::AddTraffic(), and ns3::PowerControlMobComEnv::RegisterCallbacks().
GetEpcHelper()
Ptr< EpcHelper > ns3::MobComEnv::GetEpcHelper ()
Returns
a pointer to the epc helper.
Definition at line 85 of file base-environment.cc.
GetLteHelper()
Ptr< LteHelper > ns3::MobComEnv::GetLteHelper ()
Returns
a pointer to the nr helper.
Definition at line 79 of file base-environment.cc.
Referenced by AttachUEsToEnbs(), ns3::PowerControlMobComEnv::CreateTopology(), and ns3::PowerControlMobComEnv::SetScenarioAttributes().
GetSimulationDuration()
Time ns3::MobComEnv::GetSimulationDuration ()
Returns
the total simulation duration.
Definition at line 97 of file base-environment.cc.
References m_simulationDuration.
GetTypeId()
TypeId ns3::MobComEnv::GetTypeId () static
Get the type ID.
Returns
the object TypeId.
Definition at line 11 of file base-environment.cc.
Member Data Documentation
m_notificationRate
const Time ns3::MobComEnv::m_notificationRate protected
The rate, at wich Notify() should be called to send the observations to python and get the agent's actions. Default = MilliSeconds(5)
Definition at line 146 of file base-environment.h.
Referenced by ScheduleNotificationEvents().
m_notificationStart
const Time ns3::MobComEnv::m_notificationStart protected
The time that Notify() should be called for the first time. Default = MilliSeconds(300)
Definition at line 149 of file base-environment.h.
Referenced by ScheduleNotificationEvents().
The documentation for this class was generated from the following files:
base-environment.h
base-environment.cc