defiance: ns3::PendulumCart Class Reference
ns3::PendulumCart Class Reference
defiance
Node that simulates the behaviour and physics of an inverted pendulum cart and can be used like any other ns3 node.
#include "pendulum-cart.h"
Public Types
typedef void(* RsrpSinrTracedCallback) (uint32_t nodeId, double cartMass, double pendulumMass, double pendulumLength, double angle, double angleVelocity, Vector position, double velocity, double acceleration, double nextAcceleration)
TracedCallback signature for car stats report.
Public Member Functions
PendulumCart (double xPos)
void DoDispose () override
void SetAcceleration (double acceleration)
Sets the acceleration of the cart in m/s² used in the next time step of the physics simulation.
void SetAngle (double angle)
Set the angle of the cart in radians: ensures that the angle stays between -pi and pi.
void SetAngleVelocity (double angleVelocity)
Set the angular velocity of the cart.
void SimulateTimeTic (double deltaT)
Simulates the physics of the pendulum-cart by using the equations of motion of an inverted pendulum. The equations of motion are based on https://en.wikipedia.org/wiki/Inverted_pendulum.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Public Attributes
TracedCallback< uint32_t, double, double, double, double, double, Vector, double, double, double > m_reportCarStatsTrace
The ReportCartStats trace source. Exporting node ID, cartMass, pendulumMass, pendulumLength, angle, angleVelocity, position, velocity, acceleration, nextAcceleration.
Protected Attributes
double m_acceleration
acceleration of the cart in m/s^2
double m_angle
angle of the pendulum in radians
double m_angleVelocity
angular velocity of the pendulum in rad/s
double m_cartMass
mass of the cart in kg
double m_nextAcceleration
double m_pendulumLength
length of the pendulum in m
double m_pendulumMass
mass of the pendulum in kg
double m_velocity
velocity of the cart in m/s
Detailed Description
Node that simulates the behaviour and physics of an inverted pendulum cart and can be used like any other ns3 node.
Definition at line 21 of file pendulum-cart.h.
Member Typedef Documentation
RsrpSinrTracedCallback
typedef void(* ns3::PendulumCart::RsrpSinrTracedCallback) (uint32_t nodeId, double cartMass, double pendulumMass, double pendulumLength, double angle, double angleVelocity, Vector position, double velocity, double acceleration, double nextAcceleration)
TracedCallback signature for car stats report.
Parameters
[in] nodeId
[in] cartMass
[in] pendulumMass
[in] pendulumLength
[in] angle
[in] angleVelocity
[in] position
[in] velocity
[in] acceleration
[in] nextAcceleration
Definition at line 84 of file pendulum-cart.h.
Member Function Documentation
GetTypeId()
TypeId ns3::PendulumCart::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 13 of file pendulum-cart.cc.
References m_acceleration, m_angle, m_angleVelocity, m_cartMass, m_nextAcceleration, m_pendulumLength, m_pendulumMass, m_reportCarStatsTrace, and m_velocity.
SetAngle()
void ns3::PendulumCart::SetAngle (double angle)
Set the angle of the cart in radians: ensures that the angle stays between -pi and pi.
Parameters
angle the angle of the cart in radians
Definition at line 109 of file pendulum-cart.cc.
References m_angle.
Referenced by SimulateTimeTic().
SetAngleVelocity()
void ns3::PendulumCart::SetAngleVelocity (double angleVelocity)
Set the angular velocity of the cart.
Parameters
angleVelocity the angular velocity of the cart in rad/s
Definition at line 125 of file pendulum-cart.cc.
References m_angleVelocity.
SimulateTimeTic()
void ns3::PendulumCart::SimulateTimeTic (double deltaT)
Simulates the physics of the pendulum-cart by using the equations of motion of an inverted pendulum. The equations of motion are based on https://en.wikipedia.org/wiki/Inverted_pendulum.
Parameters
deltaT the time step in seconds between recalculating the physics of the cart
Definition at line 139 of file pendulum-cart.cc.
References m_acceleration, m_angle, m_angleVelocity, m_cartMass, m_nextAcceleration, m_pendulumLength, m_pendulumMass, m_reportCarStatsTrace, m_velocity, and SetAngle().
Referenced by ns3::EnvironmentCreator::CreateCarts().
Member Data Documentation
m_nextAcceleration
double ns3::PendulumCart::m_nextAcceleration protected
acceleration that is applied in the next timestep to synchronize physics of the cart in m/s^2
Definition at line 103 of file pendulum-cart.h.
Referenced by GetTypeId(), SetAcceleration(), and SimulateTimeTic().
The documentation for this class was generated from the following files:
pendulum-cart.h
pendulum-cart.cc